### ISSUE TITLE
Refactor Tracker

### ISSUE THREAD

**Issue by keithrfung** [microsoft/electionguard-python#322]
## Issue

**Description**
- [x] Refactor `tracker_hash` to `code` in code
- [x] Refactor tracker has to Verification Code in docs
- [x] Remove `words.py` and associated tests and methods

`tracker_hash` should be refactored to `code` and similar methods should be adjusted to no longer refer it by this name. The use of this has led to confusion with many vendors. The plan is to switch to `ballot.code` which makes a bit more sense in plain english since this ends up being a top level term. 

The tracking words will be removed around the same time. This implementation is a carryover and provides some convenience but the string representation of the code can be adjust to create many useful presentations besides the one currently offered. The words also present a maintenance problem in the long term.
